version: '3.4'

services:
  settlementautomationapi:
    image: settlementautomationapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 203:203
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server/app.js"]
